name: Object-API - Build

on:
  workflow_dispatch

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set the Image TAG
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -f build/object-service/Dockerfile \ -t sanketika/object-service:${{ env.IMAGE_TAG }}_${{ github.run_number }} \ .

      - name: Push Docker image
        run: |
          docker push sanketika/object-service:${{ env.IMAGE_TAG }}_${{ github.run_number }}
