name: Object-API - Build

on:
  workflow_dispatch

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install maven -y

      - name: Maven Build
        run: |
          mvn clean install
          cd content-api/content-service
          mvn play2:dist

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: krutika03
          password: 2ke18me033@K

      - name: Set the Image TAG
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -f build/content-service/Dockerfile -t krutika03/content-service:${{ env.IMAGE_TAG }}_${{ github.run_number }} .

      - name: Push Docker image
        run: |
          docker push krutika03/content-service:${{ env.IMAGE_TAG }}_${{ github.run_number }}
